config/routes.rb
Rails.application.routes.draw do
  resource :credits, only: [:create] do
    collection do
      post '/pay', to: 'credits#pay'
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
 
  resources :users, only: [:create, :show] do
    member do
      get :items
    end
    collection do
      get  :sign_up_sns
      get  :sign_up_user_info
      post :sign_up_phone
      post :sign_up_sms
      post :sign_up_shipping
      post :sign_up_credit
      get  :sign_up_complete
    end
  end

  root 'items#index'
  get "items/hidden" => "items#hidden"
  
  resources :users, only: [:show, :edit] do
    member do
      get  :profile
      get  :logout
    end
  end

  resources :pictures, only: [:new, :create]

  resources :items, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get  :purchase_confirmation
      post :purchase
      get  :purchase_complete
    end
    collection do
      get :search
      get :category
    end
  end
  
  resources :purchases, only: [:new]

end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :pictures, dependent: :destroy
  belongs_to :shipping
  belongs_to :user
  belongs_to :category 
  has_many :orders
  validates :name, :price,:condition_id, :category_id,:shipping_from, :shipping_day_id, :status_id, presence: true
  
  belongs_to_active_hash :size
  belongs_to_active_hash :condition
  belongs_to_active_hash :cost_burden
  belongs_to_active_hash :shipping_day
  
  belongs_to_active_hash :status
  # has_many :orders, dependent: :destroy
  # has_many :likes, dependent: :destroy
  
  scope :price, -> (min, max) { 
    if min.blank? && max.blank?
      all
    elsif  min.blank?
      where('price < ?', max.to_i) 
    elsif max.blank?
      where('price > ?', min.to_i) 
    else
      where('price between ? and ?', min.to_i, max.to_i)
    end}
  scope :search, -> (keyword){ where((["name LIKE ?"] * keyword.size).join(" AND "), *keyword.map{|w| "%#{w}%"}) }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :still_selling?, only: [:purchase_confirmation, :purchase]
  before_action :set_item, only: [:edit, :destroy, :show, :update,:purchase_confirmation, :purchase]
  before_action :user_signed_in?, only: [:new, :edit, :destroy, :show, :update,:purchase_confirmation, :purchase]
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy, :update, :purchase_confirmation, :purchase, :purchase_complete]

  def index
    if user_signed_in?
      @items = Item.where.not(user_id: current_user.id).last(10)
    else
      @items = Item.all.last(10)
    end
  end

  def show
    @item = Item.find(params[:id])
    if user_signed_in?
      @items = Item.where.not(user_id: current_user.id).last(10)
    else
      @items = Item.all.last(10)
    end
    @big_categories = Category.where(ancestry: nil)
  end

  def edit
    @user = current_user
    @pictures = @item.pictures
    @big_categories = Category.where(ancestry: nil)
    @item_category = @item.category
  end
  
  def new
    @big_categories = Category.where(ancestry: nil).where.not(name: "カテゴリ一覧" )
    @middle_categories = Category.where(ancestry: params[:big_category]) if params[:big_category]
    @small_categories = Category.where(ancestry: params[:middle_category]) if params[:middle_category]
    @item = Item.new
    respond_to do |format|
      format.json
      format.html
    end
  end
  
  def create
    @item = Item.new(item_params)
    
    if @item.save
      unless params[:delete].blank?
        d = params[:delete].split(",").map{|i| i.to_i}
        d.sort!{|a,b| b<=>a}
        d.each do |i|
          params[:item][:image].delete_at(i)
        end
      end
      params[:item][:image].take(10).each do |image|
        @picture = Picture.new(image: image, item_id: @item.id)
        unless @picture.save
          render action: :new
        end
      end
      respond_to do |format|
        format.html
      end
      redirect_to root_path
    else
      redirect_to new_item_path
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      if params[:item][:image] != nil
        params[:item][:image]&.take(10-@item.pictures.length).each do |image|
          @picture = Picture.new(image: image, item_id: @item.id)
          unless @picture.save
            render action: :new
          end
        end
      end
      unless params[:delete].blank?
        d = params[:delete].split(",").map{|i| i.to_i}
        d.sort!{|a,b| b<=>a}
        d.each do |i|
          @item.pictures[i].destroy
        end
      end
      respond_to do |format|
        format.html
      end
      redirect_to root_path
    else
      redirect_to new_item_path
    end
  end
  
  def destroy
    if @item.user.id == current_user.id
      @item.destroy
      redirect_to profile_user_path(current_user)
    else
      redirect_to root_path
    end
  end
  
  def purchase_confirmation
    @category = @item.category
    @user = current_user
    create_token(@user)
    @shipping = @user.shippings.first
    @shipping_pref = Prefecture.find_by(id: @shipping.pref)
    @customer = Payjp::Customer.retrieve(@credit.token)
  end
  
  def purchase
    @category = @item.category
    #購入ユーザーを仮で作成
    @user = current_user
    create_token(@user)
    if Payjp::Charge.create(amount: @item.price,customer: @credit.token,currency: 'jpy')
      @user.balance -= @item.price
      @user.update(balance: @user.balance)
      @item.update(status_id: 2)
      @order = Order.create(item_id: @item.id, purchase_user_id: @user.id, item_status: @item.status_id)
      redirect_to purchase_complete_item_path
    else
      redirect_to purchase_confirmation_item_path
    end
    
  end

  def purchase_complete
  end

  def search
    @prices = Price.all
    @conditions = Condition.all
    @cost_burden = CostBurden.all
    @status = Status.all
    @keyword = params[:keyword].to_s.split(/[[:blank:]]+/)
    @items = Item.price( params[:min_price], params[:max_price]).search(@keyword).where(search_params).page(params[:page]).per(4)
    if @items.blank?
      @items = Item.page(params[:page]).per(2)
      @count=0
    end
  end

  def category
    @category = Category.find(params[:category_id])
    @items = Item.where(category_id: @category.subtree_ids).page(params[:page]).per(2)
  end
  
  private
  
  def create_token(user)
    Payjp.api_key = Rails.application.credentials.dig(:payment_secret_key)
    @credit = user.credits.first
  end

  def still_selling?
    @item = Item.find(params[:id])
    if @item.status_id != 1
      redirect_to root_path
    end
  end

  def item_params
    shipping = Shipping.find_by(user_id: current_user.id)
    params.require(:item).permit(:name,:text, :size_id,:condition_id, :cost_burden_id, :shipping_from, :shipping_day_id, :rating, :status_id, :category_id).merge(price: params[:price],user_id: current_user.id, shipping_id: shipping.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def search_params
    params.permit(:category_id, :brand_id, :size_id, :condition_id, :cost_burden, :status_id).reject{|k,v| v.blank?}
  end
end

app/views/items/_delete_dialog.html.haml
.dialog
.dialog_content
  %h1 確認
  %h2 削除すると二度と復活できません。
  %h2 削除する代わりに停止することもできます。
  　　　
  %h2 本当に削除しますか？
  .dialog_content_btn
    = link_to "キャンセル", "#", class:"dialog_content_btn_cancel"
    = link_to "削除する", "/items/#{@item.id}", class:"dialog_content_btn_delete", method: "DELETE"

app/views/items/_header.html.haml
.header
  .header__inner
    .header__inner__top
      .header__inner__top__mark
        = link_to root_path do
          %img{:alt => "mercari", :height => "36", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3611986733", :width => "134"}/
      = form_with(url: search_items_path, method: :get, class: "header__inner__top__form", local: true) do |f|
        = f.search_field :keyword, placeholder: "何かお探しですか？", class: "header__inner__top__form__input"
        = button_tag type: 'submit', class: "header__inner__top__form__icon" do
          %i.fa.fa-search

    .header__inner__nav
      .left-box
        .left-box__category
          = link_to "#" do
            %i.fa.fa-list-ul カテゴリーから探す
          .left-box__category-dropdown
            %ul.left-box__category-dropdown-big-category.display_none
              - @categories.select{|n| n.ancestry == nil}.each do |big_category|
                = link_to big_category.name, category_items_path(category_id: big_category.id), class: "left-box__category-dropdown-big-category-btn dropdown-btn"
                %ul.left-box__category-dropdown-middle-category
                  - @categories.select{|n| n.ancestry == big_category.id.to_s}.each do |middle_category|
                    = link_to middle_category.name, category_items_path(category_id: middle_category.id),class: "left-box__category-dropdown-middle-category-btn dropdown-btn"
                    %ul.left-box__category-dropdown-small-category.display_none#small_category
                      - @categories.select{|n| n.ancestry == big_category.id.to_s + "/"+middle_category.id.to_s}.each do |small_category|
                        = link_to small_category.name, category_items_path(category_id: small_category.id), class: "left-box__category-dropdown-small-category-btn dropdown-btn"
        .left-box__brand
          = link_to "#" do
            %i.fa.fa-tag
            ブランドから探す
            .left-box__brand-dropdown.display_none
              %ul.left-box__brand-dropdown-list
                = link_to "シャネル", "#",class: "left-box__brand-dropdown-list-btn"
                = link_to "ナイキ", "#",class: "left-box__brand-dropdown-list-btn"
                = link_to "ルイヴィトン", "#",class: "left-box__brand-dropdown-list-btn"
                = link_to "シュプリーム", "#",class: "left-box__brand-dropdown-list-btn"
                = link_to "アディダス", "#",class: "left-box__brand-dropdown-list-btn"
                = link_to "ブランド一覧", "#",class: "left-box__brand-dropdown-list-btn"        
      .right-box
        - if user_signed_in?
          .liked-items
            = link_to "#" do
              %i.far.fa-heart
              いいね！一覧
          .notification-list
            = link_to "#" do
              %i.far.fa-bell
              お知らせ
          .todo-list
            = link_to "/users/#{current_user.id}" do
              %i.fa.fa-check
              やることリスト
          .mypage-box
            = link_to "/users/#{current_user.id}" do
              %i.far.fa-file-image
              マイページ
        - unless user_signed_in?
          .header-sing-up-btn
            = link_to "新規登録", "/users/sign_up_sns", class: 'get'
          .header-sing-in-btn
            = link_to "ログイン", new_user_session_path, class: 'get'

app/views/items/_item-box.html.haml
- items.each do |item|
  %li.list_item
    = link_to item_path(item) do
      .item-box
        - if item.status_id != 1
          .item-box__sold
            sold
        .item-box__price
          = "¥" + item.price.to_s(:delimited)
        %img.lazyloaded.is-higher-width{:alt => item.name, "data-src" => item.name, :src => item.pictures.first.image.url}
        %h2 
          = item.name

app/views/items/_item-box_show.html.haml
- items.first(6).each do |item|
  %li.list_item
    = link_to item_path(item) do
      .item-box-show
        - if item.status_id != 1
          .item-box-show__sold
            sold
        - if item&.pictures != nil
          %img.lazyloaded.is-higher-width{:alt => item.name, "data-src" => item.name, :src => item.pictures.first.image.url}
        %h2.item-box-show_item_name
          = item.name
        %h2.item-box-show_item_price
          = "¥" + item.price.to_s(:delimited)

app/views/items/_search-item-box.html.haml
%li.search-item-box
  %img.search-item-box__image{:alt => item.name, "data-src" => item.name, :src => item.pictures.first.image.url}
  .search-item-box__body
    %h3= item.name
    %h2= "¥" + item.price.to_s(:delimited)

app/views/items/_sell-btn.html.haml
.sell-btn
  - if user_signed_in?
    = link_to "/items/new" do
      %div 出品 
      %i.fas.fa-camera  
  - else
    = link_to "/users/sign_in" do
      %div 出品 
      %i.fas.fa-camera

app/views/items/category.html.haml
.container
  = render partial: 'header'
  = render partial: 'devise/registrations/bread-crumbs'

  .category-main-box
    %h2= "#{@category.name}の商品一覧"
    - if @items.empty?
      %p 該当する商品が見つかりません。検索条件を変えて、再度お試しください。
    %ul.search-list
      = render partial: 'search-item-box', collection: @items, as: :item
    = paginate(@items, window: 2)
      

  
  = render partial: 'bottom'
  = render partial: 'sell-btn'

app/views/items/edit.html.haml
= form_with model: @item, id: "edit_item" do |f|
  .register_header
    .register_header_logo
      = image_tag 'mercari_logo.png'

  .edit-main
    .edit-main__box
      .edit-content
        %h2.edit-content__header
          商品の情報を入力  

        .edit-content__form
          .edit-upload-box
            %h3.edit-upload-box__head
              出品画像
              %span 必須
            %p 最大10枚までアップロードできます
            .edit-upload-box__drop
              .edit-upload-box__drop_wrap
                .drop-box-input
                  = f.file_field :image, multiple: true,class: "image_field",accept: "image/*"
                  %p 
                    ドラックアンドドロップ
                    %br
                      またはクリックしてファイルをアップロード
                  - @pictures.each_with_index do |picture, index|
                    %div{class: "drop-box-input_upload #{index}"}
                      %img.photo{:class => "image_#{index} #{index}", :src => picture.image.url}/
                      .drop-box-input_upload_edit
                        %span.drop-box-input_upload_edit_btn.drop-box-input_upload_btn{:class => "image_edit_#{index} #{index}"} 編集
                        %span.drop-box-input_upload_delete_btn.drop-box-input_upload_btn{:class => "image_delete_#{index} #{index}"} 削除
          .edit-item
            .edit-item__name
              商品名
              %span 必須
              .edit-item__name__input
                = f.text_area :name, placeholder: "商品名（必須 40文字まで)", value: @item.name,class: "input-default"
            .edit-item__discription
              商品の説明
              %span 必須
              .edit-item__discription__text
                = f.text_area :text, class:"textarea-default", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", rows: "5",value: @item.text

          .edit-content
            %h3.edit-content__head
              商品の詳細
            .edit-content__select-box
              .select-pulldown
                カテゴリー
                %span 必須

                .select-wrap
                  %i.fas.fa-chevron-down
                  = f.collection_select(:big_category_id, @big_categories, :id, :name ,class:"big_category_select", selected: @item_category.root.id)
                  - @big_categories.each do |big_category|
                    - if big_category.children.ids.include?(@item_category.parent.id)
                      = f.collection_select(:middle_category_id, big_category.children, :id, :name, {prompt: "カテゴリを選択してください", selected: @item_category.parent.id} ,class:"middle_category_select middle-#{big_category.id}", style: "display: block")
                    -else
                      = f.collection_select(:middle_category_id, big_category.children, :id, :name, {prompt: "カテゴリを選択してください"} ,class:"middle_category_select middle-#{big_category.id}")
                    - big_category.children.each do |middle_category|
                      - if middle_category.children.ids.include?(@item_category.id)
                        = f.collection_select(:small_category_id, middle_category.children, :id, :name, {prompt: "カテゴリを選択してください", selected: @item_category.id} ,class:"small_category_select small-#{middle_category.id}", style: "display: block")
                      - else
                        = f.collection_select(:small_category_id, middle_category.children, :id, :name, {prompt: "カテゴリを選択してください"} ,class:"small_category_select small-#{middle_category.id}")
                  = f.hidden_field :category_id, value: @item_category.id
                  - if @item.size_id
                    = f.collection_select :size_id, Size.all, :id, :name, selected: @item.size_id, class: "size_id select-default"
                    
            .edit-content__select-add-box
              .select-pulldown
                商品の状態
                %span 必須

                .select-wrap
                  %i.fas.fa-chevron-down
                  = f.collection_select :condition_id, Condition.all, :id, :name, selected: @item.condition_id, class: "condition_id select-default"
          .edit-content
            %h3.edit-content__head
              配送について
            .edit-content__select-box
              .select-pulldown
                配送料の負担
                %span 必須

                .select-wrap
                  %i.fas.fa-chevron-down
                  = f.collection_select :cost_burden_id, CostBurden.all, :id, :name, selected: @item.cost_burden_id, class: "cost_burden_id select-default"
            .edit-content__select-add-box
              .select-pulldown
                発送元の地域
                %span 必須
                .select-wrap
                  %i.fas.fa-chevron-down
                  = f.collection_select :shipping_from, Prefecture.all, :id, :name, selected: @item.shipping_from, class: "prefecture_id select-default"


            .edit-content__select-add-box
              .select-pulldown
                発送までの日数
                %span 必須

                .select-wrap
                  %i.fas.fa-chevron-down
                  = f.collection_select :shipping_day_id, ShippingDay.all, :id, :name, selected: @item.shipping_day_id, class: "shipping_day_id select-default"
          .edit-content
            %h3.edit-content__head
              販売価格(300~9,999,999)
            .edit-content__select-box
              %li.select-decide
                .select-decide__price
                  価格
                  %span 必須
                .select-decide__input
                  ¥
                  = f.text_field :price, type: "number", placeholder: "例）300", value: @item.price, name: "price",oninput: "vop2.value = Number(price.value) - Number(price.value) / 10, vop1.value = Number(price.value) / 10;"
              .fee-box
                .fee-box__left
                  販売手数料(10%)
                .fee-box__right
                  %output{name: "vop1"}
                    ¥
                    = @item.price / 10

              .profit-box
                .profit-box__left
                  販売利益
                .profit-box__right
                  %output{name: "vop2"}
                    ¥
                    = (@item.price * 9) / 10
          .edit-btn-box
            .edit-btn-box__note
              禁止されている出品、行為を必ずご確認ください。
              %br
              またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
              %br
              また、出品をもちまして加盟店規約に相違したことになります。
            .edit-btn-box__push
              %button.btn-default{type: "submit"} 変更する
            .edit-btn-box__back
              = link_to root_path do
                .btn-default
                  もどる



  %nav.footer
    %ul
      %li
        = link_to "プライバシーポリシー", "#"
      %li
        = link_to "メルカリ利用規約", "#"
      %li
        = link_to "特定商取引に関する表記", "#"
    = image_tag 'mercari_logo2.png'
    %p ©︎2019 Mercari

app/views/items/hidden.html.haml
%p= link_to "トップページ", root_path

user_path
%p= link_to "new_user_session", new_user_session_path
-# %p= link_to "users_sign_up_payment_confirmation", users_sign_up_payment_confirmation_path

%p= link_to "sign_up_sns_users", sign_up_sns_users_path
%p= link_to "sign_up_user_info_path", sign_up_user_info_users_path
%p= link_to "※sign_up_phone_users_path", sign_up_phone_users_path
%p= link_to "※sign_up_sms_users_path", sign_up_sms_users_path
%p= link_to "※sign_up_shipping_users_path", sign_up_shipping_users_path
%p= link_to "※sign_up_credit_users_path", sign_up_credit_users_path
-# %p= link_to "", _path

items
%p= link_to "search_items_path", search_items_path

picture
%p= link_to "new_picture", new_picture_path

- if user_signed_in?
  users
  %p= link_to "users#show", user_path(id: current_user.id)
  %p= link_to "users#edit", edit_user_path(id: current_user.id)
  %p= link_to "users#profile", profile_user_path(id: current_user.id)
  %p= link_to "users#destroy　マージするときに削除　それまで仮置き", destroy_user_session_path, method: "DELETE"
  item
  %p= link_to "items#index", items_path
  - if current_user.items.length != 0
    %p= link_to "items#show", item_path(id: current_user.items.first.id)
    %p= link_to "items#edit", edit_item_path(id: current_user.items.first.id)
  %p= link_to "items#new", new_item_path
  

app/views/items/index.html.haml
.container
  = render partial: 'header'

  .main
    
    .main__owl 
      -# 非同期にてスライドするところ
      .main__owl__content
        %h2 
          スマホでかんたん
          %br 
          フリマアプリ
        %p
          メルカリはスマホカメラからすぐに出品できる
          %br
          購入時も安心な独自システムのアプリです
        .main__owl__content__icon
          %ul
            %li
              = link_to "https://apps.apple.com/jp/app/id667861049?l=ja" do
                %img{:alt => "", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?4248847005"}/
            %li
              = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja" do
                %img{:alt => "", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?4248847005"}/
      .main__owl__image
        %img{:alt => "", :src => "//www-mercari-jp.akamaized.net/assets/img/common/jp/top/main_content_pc.png?4248847005"}/
  .main-content
    .pickup
      .pickup__header
        %h2 ピックアップカテゴリー
        .pickup__header__type
          レディース新着アイテム
          = link_to "もっと見る＞", "#"
        .pickup__header__item
          %ul.pickup__header__item-list
            = render 'item-box', items: @items
      .pickup__header
        %h2 ピックアップブランド
        .pickup__header__type
          シャネル新着アイテム
          = link_to "もっと見る＞", "#"
        .pickup__header__item
          %ul.pickup__header__item-list
            = render 'item-box', items: @items
  
  = render partial: 'bottom'

  = render partial: 'sell-btn'

app/views/items/purchase_complete.html.haml
-# ここからpまでが新規登録画面5　住所画面
.register_header
  .register_header_logo
    = image_tag 'mercari_logo.png'
    -# 写真は本番のときに改めて差し替える
.register_user_register5
  .register_user_register5_contents
    %h1 購入完了
    = link_to "トップページに戻る", root_path, class: "btn"
    %br
-#       = link_to "本人情報の登録について＞", "#", style: "text-align: right;"

%nav.footer
  %ul
    %li
      = link_to "プライバシーポリシー", "#"
    %li
      = link_to "メルカリ利用規約", "#"
    %li
      = link_to "特定商取引に関する表記", "#"
  = image_tag 'mercari_logo2.png'
  -# 写真は本番のときに改めて差し替える
  %p ©︎2019 Mercari

app/views/items/purchase_confirmation.html.haml
.register_header
  .register_header_logo
    = image_tag 'mercari_logo.png'
.buy-main
  .buy-main__box
    .buy-content
      %h2.buy-content__header
        購入内容の確認
      .buy-content__item
        .buy-content__item__inner
          .buy-item-main
            .buy-item-image
              = image_tag @item.pictures.first.image.url, height: "64px" , width: "64px"
            .buy-item-name
              = @item.name
          %form.buy-form
            %p.buy-price
              ¥
              = @item.price.to_s(:delimited)
              %span送料込み
            .buy-have-point
              ポイントはありません
            .buy-price-table
              .buy-price-table__left
                支払金額
              .buy-price-table__right
                ¥
                = @item.price.to_s(:delimited)
            - if @user.balance >= @item.price && @item.status_id == 1
              = link_to "購入する", purchase_item_path(@item), method: "POST" ,class:"btn-default"
            - elsif @user.balance < @item.price
              = link_to "残高不足のため購入できません", root_path, method: "GET" ,class:"btn-default",style: "background-color: lightgray"
            - else 
              = link_to "取引が終了したアイテムです", root_path, method: "GET" ,class:"btn-default",style: "background-color: lightgray"
      .buy-content__user-info
        .buy-content__user-info__inner
          %h3 配送先
          .user-info-text
            〒
            = @shipping.zipcode.to_s.insert(3, " - ")
            %br
            = @shipping_pref.name + @shipping.city + @shipping.address + @shipping.building
            %br
            = @user.last_name_kanji + " " + @user.first_name_kanji

          .user-info-fix
            = link_to "#" do
              変更する
              %span 
              %i.fas.fa-chevron-right
      .buy-content__user-info
        .buy-content__user-info__inner
          %h3 支払方法

          .user-info-text
            ************
            = @customer.cards.retrieve(@customer.cards.first.id).last4
            %br
            = @customer.cards.retrieve(@customer.cards.first.id).exp_month
            \/
            = @customer.cards.retrieve(@customer.cards.first.id).exp_year-2000
            %br
            - if @customer.cards.retrieve(@customer.cards.first.id).brand == "Visa"
              = image_tag "/visacard.png", width: "34px", style: "background-color: blue"
            - elsif @customer.cards.retrieve(@customer.cards.first.id).brand == "MasterCard"
              = image_tag "/mastercard.png", width: "34px"
            - elsif @customer.cards.retrieve(@customer.cards.first.id).brand == "Diners Club"
              = image_tag "/diners_clubcard.png", width: "34px"
            - elsif @customer.cards.retrieve(@customer.cards.first.id).brand == "American Express"
              = image_tag "/american_expresscard.png", width: "34px"
            - elsif @customer.cards.retrieve(@customer.cards.first.id).brand == "JCB"
              = image_tag "/jcbcard.png", width: "34px"
            - else @customer.cards.retrieve(@customer.cards.first.id).brand == "Discover"
              = image_tag "/discover.png", width: "34px"
          .user-info-fix
            = link_to "#" do
              変更する
              %span
              %i.fas.fa-chevron-right


%nav.footer
  %ul
    %li
      = link_to "プライバシーポリシー", "#"
    %li
      = link_to "メルカリ利用規約", "#"
    %li
      = link_to "特定商取引に関する表記", "#"
  = image_tag 'mercari_logo2.png'
  %p ©︎2019 Mercari

app/views/items/search.html.haml
.container
  = render partial: 'items/header'

  = render partial: 'devise/registrations/bread-crumbs'

  .main-box
    = render partial: 'items/search-sidebar'
    .search-main
      %h2.search-result 
        = @keyword.join(",")
        %span の検索結果
      - if @count == 0
        %p 該当する商品が見つかりません。検索条件を変えて、再度お試しください。
        %h3.latest-item  新着商品
      - else
        .search_count
          = page_entries_info @items, entry_name: 'item'
      %ul.search-list
        = render partial: 'search-item-box', collection: @items, as: :item
      = paginate(@items, window: 2)

  = render partial: 'items/bottom'

  = render partial: 'items/sell-btn'